[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xml2xlsx-lidilem"
version = "0.3.0.2"
description = "Convertisseur XML annoté vers Excel (corpus littéraires PREFAB)"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "openpyxl",
    "pandas",
    "numpy",
    "lxml",
    "tk"
]

[project.scripts]
xml2xlsx = "xml2xlsx.xml2xlsx:main"
xml2xlsx-gui = "xml2xlsx.gui:main"
